use yaml.safe_load instead of yaml.load()
This to avoid the following error:

`TypeError: load() missing 1 required positional argument: 'Loader'`# Please enter the commit message for your changes. Lines starting